# Generated by Django 4.2.14 on 2024-08-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0002_order_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
