# Generated by Django 4.2.14 on 2024-08-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_service', '0002_alter_publisher_website'),
        ('order_service', '0003_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'book')},
        ),
    ]
