# Generated by Django 4.2.14 on 2024-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_service', '0002_alter_publisher_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['publication_date']},
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select book genre', related_name='books', to='book_service.genre'),
        ),
    ]
